name: Deploy to ECR

on:
    push:
        branches:
            - main

jobs:
    deploy:
        if: ${{ !contains(github.event.head_commit.message, 'dependabot') }}
        name: Build Image
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v2

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-2

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1

            - name: Build, tag, and push image to Amazon ECR
              id: build-image
              env:
                  ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                  ECR_REPOSITORY: personal-site-24
                  IMAGE_TAG: ${{ github.sha }}
              run: |
                  docker build --build-arg COMMON_MD_DIR=${{ secrets.COMMON_MD_DIR }} --build-arg MD_ASSET_DIR=${{ secrets.MD_ASSET_DIR }} -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG . --no-cache
                  docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
                  echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
